const express = require("express");
const multer = require("multer");
const authMiddleware = require("../middleware/authMiddleware");
const examModuleController = require("../controllers/examModuleController");

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage() });

router.post("/login", examModuleController.loginStudent);
router.post("/admin/login", examModuleController.loginAdmin);
router.get("/admin/exams", authMiddleware, examModuleController.listExamsForAdmin);
router.post("/admin/exams", authMiddleware, examModuleController.createExamByAdmin);
router.patch("/admin/exams/:examId/toggle", authMiddleware, examModuleController.toggleExamByAdmin);
router.patch("/admin/exams/:examId/result-visibility", authMiddleware, examModuleController.updateResultVisibilityByAdmin);
router.delete("/admin/exams/:examId", authMiddleware, examModuleController.deleteExamByAdmin);
router.get("/admin/exams/:examId/assignments", authMiddleware, examModuleController.listExamAssignmentsByAdmin);
router.get("/admin/exams/:examId/assignment-logs", authMiddleware, examModuleController.listAssignmentAuditLogsByAdmin);
router.post("/admin/exams/:examId/assignments", authMiddleware, examModuleController.assignStudentsToExamByAdmin);
router.delete("/admin/exams/:examId/assignments/:studentId", authMiddleware, examModuleController.removeStudentAssignmentByAdmin);
router.patch("/admin/exams/:examId/assignments/:studentId/result-visibility", authMiddleware, examModuleController.updateStudentResultVisibilityByAdmin);
router.get("/admin/exams/:examId/questions", authMiddleware, examModuleController.getExamQuestionsForAdmin);
router.post("/admin/exams/:examId/questions", authMiddleware, examModuleController.createExamQuestionsByAdmin);
router.put("/admin/exams/:examId/questions/:questionId", authMiddleware, examModuleController.updateExamQuestionByAdmin);
router.delete("/admin/exams/:examId/questions/:questionId", authMiddleware, examModuleController.deleteExamQuestionByAdmin);
router.get("/admin/students", authMiddleware, examModuleController.listStudentsByAdmin);
router.post("/admin/students", authMiddleware, examModuleController.createStudentByAdmin);
router.patch("/admin/students/status/bulk", authMiddleware, examModuleController.bulkUpdateStudentStatusByAdmin);
router.patch("/admin/students/:studentId", authMiddleware, examModuleController.updateStudentByAdmin);
router.patch("/admin/students/:studentId/status", authMiddleware, examModuleController.updateStudentStatusByAdmin);
router.post("/admin/students/bulk-upload", authMiddleware, upload.single("file"), examModuleController.bulkUploadStudentsByAdmin);
router.get("/admin/institutes", authMiddleware, examModuleController.listInstitutesByAdmin);
router.post("/admin/institutes", authMiddleware, examModuleController.createInstituteByAdmin);
router.patch("/admin/institutes/:instituteId", authMiddleware, examModuleController.updateInstituteByAdmin);
router.delete("/admin/institutes/:instituteId", authMiddleware, examModuleController.deleteInstituteByAdmin);
router.get("/admin/recycle-bin/institutes", authMiddleware, examModuleController.listDeletedInstitutesByAdmin);
router.patch("/admin/recycle-bin/institutes/:instituteId/restore", authMiddleware, examModuleController.restoreInstituteByAdmin);
router.delete("/admin/recycle-bin/institutes/:instituteId/permanent", authMiddleware, examModuleController.permanentlyDeleteInstituteByAdmin);
router.get("/admin/groups", authMiddleware, examModuleController.listGroupsByAdmin);
router.post("/admin/groups", authMiddleware, examModuleController.createGroupByAdmin);
router.patch("/admin/groups/:groupId", authMiddleware, examModuleController.updateGroupByAdmin);
router.delete("/admin/groups/:groupId", authMiddleware, examModuleController.deleteGroupByAdmin);
router.get("/admin/recycle-bin/groups", authMiddleware, examModuleController.listDeletedGroupsByAdmin);
router.patch("/admin/recycle-bin/groups/:groupId/restore", authMiddleware, examModuleController.restoreGroupByAdmin);
router.delete("/admin/recycle-bin/groups/:groupId/permanent", authMiddleware, examModuleController.permanentlyDeleteGroupByAdmin);
router.get("/admin/results", authMiddleware, examModuleController.listResultsByAdmin);
router.get("/admin/results/export", authMiddleware, examModuleController.exportResultsByAdmin);
router.get("/exams", authMiddleware, examModuleController.listExamsForStudent);
router.get("/exams/:examId/instructions", authMiddleware, examModuleController.getExamInstructions);
router.get("/exams/:examId/questions", authMiddleware, examModuleController.getExamQuestions);
router.get("/exams/:examId/result", authMiddleware, examModuleController.getStudentExamResult);
router.post("/exams/:examId/submit", authMiddleware, examModuleController.submitExam);

module.exports = router;
